name: Bug Report
title: "[Bug]: "
description: "Use this template if you're running into bugs or other issues"
labels:
  - C-Bug
  - C-Needs-Work
body:
  - type: markdown
    attributes:
      value: >-
        ## Instructions


        This is a template for the issue you are about to open! It will help you
        provide the information necessary to complete your **bug report**.
        Before you open an issue, ensure you've completed every step on the
        checklist below.


        - Have you used the [search
        tool](https://github.com/SteamworkMC/Seaborgium/issues) to find
        similar issues? If you found one similar to the issue you're reporting,
        please comment on it instead, rather than creating a duplicate.

        - Are you running the latest version of the mod? If not, please update.
        Things change heavily between versions, and the issue you're seeing may
        already be resolved.


        All good? Then continue to fill the issue by providing the following
        information about it:
  - type: input
    id: version
    attributes:
      label: Version information
      description: >-
        Please provide the exact version of the mod you are using. Every part of
        the version is important! If you do not know what version you are using,
        look at the file name in your `mods` folder.
      placeholder: 'Example: seaborgium-mc1.19.4-0.1.3'
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
      placeholder: 'Example: The world should be rendering properly'
    validations:
      required: true
  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What did actually happen?
      placeholder: 'Example: Doors are floating away from where they should be'
    validations:
      required: true
  - type: textarea
    id: repro-steps
    attributes:
      label: Reproduction Steps
      description: >-
        Provide information on how to reproduce this bug. You can either
        fill this section in like the example below or do something else just
        make sure your instructions are minimal and clear, as other people will
        need to be able to replicate your issue.
      placeholder: |
        Example:
        1. Place a Redstone Lamp in front of a Redstone Repeater
        2. Use a Lever to activate the Redstone Repeater
        3. Nothing happens
    validations:
      required: true
  - type: markdown
    attributes:
      value: >-
        # System Information


        You can obtain this information from the right-side of the in-game debug
        screen (F3) or through using
        [DxDiag](https://support.microsoft.com/en-us/help/4028644/windows-open-and-run-dxdiagexe)
        on Windows. 
  - type: input
    id: java
    attributes:
      label: Java version
      placeholder: 'Example: Java 16'
    validations:
      required: true
  - type: input
    id: cpu
    attributes:
      label: CPU
      placeholder: 'Example: Intel Core i5-7200U'
    validations:
      required: true
  - type: input
    id: gpu
    attributes:
      label: GPU
      placeholder: 'Example: Intel HD Graphics 620'
    validations:
      required: true
  - type: textarea
    id: additional
    attributes:
      label: Additional information
      description: >-
        Provide a list of any other mods you are using, along with their
        respective versions. If you have any screenshots, videos, or other
        information that you feel is necessary to explain the issue, feel free
        to attach them here.
